// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.1.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace engine_schemas
{
namespace detail
{
namespace types
{

enum class enum_2 : char
{
    buy = 'B',
    sell = 'S'
};


inline SBEPP_CPP14_CONSTEXPR const char*
    tag_invoke(
        ::sbepp::detail::enum_to_str_tag,
        enum_2 e) noexcept
{
    switch(e)
    {
    
    case enum_2::buy:
        return "buy";

    case enum_2::sell:
        return "sell";

    default:
        return nullptr;
    }
}


} // namespace types
} // namespace detail

namespace types
{
using Side = ::engine_schemas::detail::types::enum_2;
} // namespace types
} // namespace engine_schemas

namespace sbepp
{

template<>
class enum_traits<::engine_schemas::schema::types::Side>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Side";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    using encoding_type = char;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::Side;
};

template<>
class enum_value_traits<::engine_schemas::schema::types::Side::buy>
{
public:
    static constexpr const char* name() noexcept
    {
        return "buy";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::engine_schemas::types::Side value() noexcept
    {
        return ::engine_schemas::types::Side::buy;
    }
};

template<>
class enum_value_traits<::engine_schemas::schema::types::Side::sell>
{
public:
    static constexpr const char* name() noexcept
    {
        return "sell";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::engine_schemas::types::Side value() noexcept
    {
        return ::engine_schemas::types::Side::sell;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
