// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.1.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace engine_schemas
{
namespace detail
{
namespace types
{

class type_5
    : public ::sbepp::detail::required_base<::std::uint32_t, type_5>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint32_t, type_5>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {4294967294};
    }
};

} // namespace types
} // namespace detail

namespace types
{
using UINT32 = ::engine_schemas::detail::types::type_5;
} // namespace types
} // namespace engine_schemas

namespace sbepp
{

template<>
class type_traits<::engine_schemas::schema::types::UINT32>
{
public:
    static constexpr const char* name() noexcept
    {
        return "UINT32";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint32_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::engine_schemas::types::UINT32;
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
