// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.1.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"
#include "../types/STRING20.hpp"
#include "../types/OrderStatus.hpp"
#include "../types/STRING4.hpp"
#include "../types/OrderType.hpp"
#include "../types/Side.hpp"
#include "../types/messageHeader.hpp"
#include "../types/STRING36.hpp"
#include "../types/UINT32.hpp"
#include "../types/UINT64.hpp"


namespace engine_schemas
{
namespace detail
{
namespace messages
{



template<typename Byte>
class message_1 : public ::sbepp::detail::message_base<
    Byte, ::engine_schemas::types::messageHeader<Byte>>
{
public:
    using ::sbepp::detail::message_base<
        Byte, ::engine_schemas::types::messageHeader<Byte>>::message_base;
    using ::sbepp::detail::message_base<
        Byte, ::engine_schemas::types::messageHeader<Byte>>::operator();

    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::UINT64 eventTimestamp() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::UINT64, ::engine_schemas::types::UINT64::value_type, ::sbepp::endian::little>(*this, 12);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void eventTimestamp(::engine_schemas::types::UINT64 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 12, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::UINT32 price() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::UINT32, ::engine_schemas::types::UINT32::value_type, ::sbepp::endian::little>(*this, 20);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void price(::engine_schemas::types::UINT32 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 20, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::UINT32 quantity() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::UINT32, ::engine_schemas::types::UINT32::value_type, ::sbepp::endian::little>(*this, 24);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void quantity(::engine_schemas::types::UINT32 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 24, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::UINT32 leavesQuantity() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::UINT32, ::engine_schemas::types::UINT32::value_type, ::sbepp::endian::little>(*this, 28);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void leavesQuantity(::engine_schemas::types::UINT32 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 28, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::Side side() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::Side, ::engine_schemas::types::Side, ::sbepp::endian::little>(*this, 32);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void side(::engine_schemas::types::Side v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 32, v);
    }
    constexpr ::engine_schemas::types::STRING36<Byte> orderID() const noexcept
    {
        return ::sbepp::detail::get_static_field_view<::engine_schemas::types::STRING36<Byte>>(
            *this, 33);
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::OrderType orderType() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::OrderType, ::engine_schemas::types::OrderType, ::sbepp::endian::little>(*this, 69);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void orderType(::engine_schemas::types::OrderType v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 69, v);
    }
    SBEPP_CPP20_CONSTEXPR ::engine_schemas::types::OrderStatus orderStatus() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::engine_schemas::types::OrderStatus, ::engine_schemas::types::OrderStatus, ::sbepp::endian::little>(*this, 70);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void orderStatus(::engine_schemas::types::OrderStatus v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 70, v);
    }
    constexpr ::engine_schemas::types::STRING4<Byte> instrumentID() const noexcept
    {
        return ::sbepp::detail::get_static_field_view<::engine_schemas::types::STRING4<Byte>>(
            *this, 71);
    }
    constexpr ::engine_schemas::types::STRING20<Byte> trader() const noexcept
    {
        return ::sbepp::detail::get_static_field_view<::engine_schemas::types::STRING20<Byte>>(
            *this, 75);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        eventTimestamp(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::UINT64>
    {
        return c.template get_value<::engine_schemas::types::UINT64, ::std::uint64_t, ::sbepp::endian::little>(
            *this, 0, 12);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void eventTimestamp(
        ::engine_schemas::types::UINT64 v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 12, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        price(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::UINT32>
    {
        return c.template get_value<::engine_schemas::types::UINT32, ::std::uint32_t, ::sbepp::endian::little>(
            *this, 0, 20);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void price(
        ::engine_schemas::types::UINT32 v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 20, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        quantity(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::UINT32>
    {
        return c.template get_value<::engine_schemas::types::UINT32, ::std::uint32_t, ::sbepp::endian::little>(
            *this, 0, 24);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void quantity(
        ::engine_schemas::types::UINT32 v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 24, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        leavesQuantity(Cursor&& c) const noexcept
            -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::UINT32>
    {
        return c.template get_value<::engine_schemas::types::UINT32, ::std::uint32_t, ::sbepp::endian::little>(
            *this, 0, 28);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void leavesQuantity(
        ::engine_schemas::types::UINT32 v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 28, v.value());
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        side(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::Side>
    {
        return c.template get_value<::engine_schemas::types::Side, ::engine_schemas::types::Side, ::sbepp::endian::little>(
            *this, 0, 32);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void side(
        ::engine_schemas::types::Side v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 32, v);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        orderID(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::STRING36<
            ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_static_field_view<::engine_schemas::types::STRING36<
            ::sbepp::detail::cursor_byte_type_t<Cursor>>>(
                *this, 0, 33);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        orderType(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::OrderType>
    {
        return c.template get_value<::engine_schemas::types::OrderType, ::engine_schemas::types::OrderType, ::sbepp::endian::little>(
            *this, 0, 69);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void orderType(
        ::engine_schemas::types::OrderType v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 69, v);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        orderStatus(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::OrderStatus>
    {
        return c.template get_value<::engine_schemas::types::OrderStatus, ::engine_schemas::types::OrderStatus, ::sbepp::endian::little>(
            *this, 0, 70);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_writeable_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR void orderStatus(
        ::engine_schemas::types::OrderStatus v, Cursor&& c) const noexcept
    {
        return c.template set_value<::sbepp::endian::little>(
            *this, 0, 70, v);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto
        instrumentID(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor, ::engine_schemas::types::STRING4<
            ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_static_field_view<::engine_schemas::types::STRING4<
            ::sbepp::detail::cursor_byte_type_t<Cursor>>>(
                *this, 0, 71);
    }

    template<
        typename Cursor,
        typename = ::sbepp::detail::enable_if_cursor_compatible_t<
            Byte, ::sbepp::detail::cursor_byte_type_t<Cursor>>>
    SBEPP_CPP20_CONSTEXPR auto trader(Cursor&& c) const noexcept
        -> ::sbepp::detail::cursor_result_type_t<Cursor,
            ::engine_schemas::types::STRING20<::sbepp::detail::cursor_byte_type_t<Cursor>>>
    {
        return c.template get_last_static_field_view<::engine_schemas::types::STRING20<::sbepp::detail::cursor_byte_type_t<Cursor>>>(
            *this, 0, 75);
    }


    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP14_CONSTEXPR ::engine_schemas::types::messageHeader<Byte>
        operator()(::sbepp::detail::fill_message_header_tag) const noexcept
    {
        auto header = operator()(::sbepp::detail::get_header_tag{});
        header.schemaId({1});
        header.templateId({1});
        header.version({0});
        header.blockLength({83});
        header.numGroups({0});

        header.numVarDataFields({0});

        return header;
    }


    SBEPP_CPP20_CONSTEXPR std::size_t operator()(
        ::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 12 + (*this)(::sbepp::detail::get_block_length_tag{});
    }


    template<typename Visitor, typename Cursor>
    SBEPP_CPP14_CONSTEXPR void operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor& c)
    {
        v.template on_message(*this, c, ::engine_schemas::schema::messages::order_schema{});
    }


    template<typename Visitor, typename Cursor>
    SBEPP_CPP14_CONSTEXPR bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor& c)
    {
        (void)v;
        (void)c;
        return v.template on_field(this->eventTimestamp(c), ::engine_schemas::schema::messages::order_schema::eventTimestamp{})
||v.template on_field(this->price(c), ::engine_schemas::schema::messages::order_schema::price{})
||v.template on_field(this->quantity(c), ::engine_schemas::schema::messages::order_schema::quantity{})
||v.template on_field(this->leavesQuantity(c), ::engine_schemas::schema::messages::order_schema::leavesQuantity{})
||v.template on_field(this->side(c), ::engine_schemas::schema::messages::order_schema::side{})
||v.template on_field(this->orderID(c), ::engine_schemas::schema::messages::order_schema::orderID{})
||v.template on_field(this->orderType(c), ::engine_schemas::schema::messages::order_schema::orderType{})
||v.template on_field(this->orderStatus(c), ::engine_schemas::schema::messages::order_schema::orderStatus{})
||v.template on_field(this->instrumentID(c), ::engine_schemas::schema::messages::order_schema::instrumentID{})
||v.template on_field(this->trader(c), ::engine_schemas::schema::messages::order_schema::trader{});
    }

};

} // namespace messages
} // namespace detail

namespace messages
{

    template<typename Byte>
    using order_schema = ::engine_schemas::detail::messages::message_1<Byte>;

} // namespace messages
} // namespace engine_schemas

namespace sbepp
{

template<>
class message_traits<::engine_schemas::schema::messages::order_schema>
{
public:
    static constexpr const char* name() noexcept
    {
        return "order_schema";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr message_id_t id() noexcept
    {
        return 1;
    }

    static constexpr block_length_t block_length() noexcept
    {
        return 83;
    }

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::engine_schemas::messages::order_schema<Byte>;

};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::eventTimestamp>
{
public:
    static constexpr const char* name() noexcept
    {
        return "eventTimestamp";
    }

    static constexpr member_id_t id() noexcept
    {
        return 1;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::UINT64;
    using value_type_tag = ::engine_schemas::schema::types::UINT64;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::price>
{
public:
    static constexpr const char* name() noexcept
    {
        return "price";
    }

    static constexpr member_id_t id() noexcept
    {
        return 2;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {8};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::UINT32;
    using value_type_tag = ::engine_schemas::schema::types::UINT32;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::quantity>
{
public:
    static constexpr const char* name() noexcept
    {
        return "quantity";
    }

    static constexpr member_id_t id() noexcept
    {
        return 3;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {12};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::UINT32;
    using value_type_tag = ::engine_schemas::schema::types::UINT32;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::leavesQuantity>
{
public:
    static constexpr const char* name() noexcept
    {
        return "leavesQuantity";
    }

    static constexpr member_id_t id() noexcept
    {
        return 4;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {16};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::UINT32;
    using value_type_tag = ::engine_schemas::schema::types::UINT32;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::side>
{
public:
    static constexpr const char* name() noexcept
    {
        return "side";
    }

    static constexpr member_id_t id() noexcept
    {
        return 5;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {20};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::Side;
    using value_type_tag = ::engine_schemas::schema::types::Side;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::orderID>
{
public:
    static constexpr const char* name() noexcept
    {
        return "orderID";
    }

    static constexpr member_id_t id() noexcept
    {
        return 6;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {21};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::engine_schemas::types::STRING36<Byte>;

    using value_type_tag = ::engine_schemas::schema::types::STRING36;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::orderType>
{
public:
    static constexpr const char* name() noexcept
    {
        return "orderType";
    }

    static constexpr member_id_t id() noexcept
    {
        return 7;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {57};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::OrderType;
    using value_type_tag = ::engine_schemas::schema::types::OrderType;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::orderStatus>
{
public:
    static constexpr const char* name() noexcept
    {
        return "orderStatus";
    }

    static constexpr member_id_t id() noexcept
    {
        return 8;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {58};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::engine_schemas::types::OrderStatus;
    using value_type_tag = ::engine_schemas::schema::types::OrderStatus;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::instrumentID>
{
public:
    static constexpr const char* name() noexcept
    {
        return "instrumentID";
    }

    static constexpr member_id_t id() noexcept
    {
        return 9;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {59};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::engine_schemas::types::STRING4<Byte>;

    using value_type_tag = ::engine_schemas::schema::types::STRING4;
};

template<>
class field_traits<::engine_schemas::schema::messages::order_schema::trader>
{
public:
    static constexpr const char* name() noexcept
    {
        return "trader";
    }

    static constexpr member_id_t id() noexcept
    {
        return 10;
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {63};
    }


    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::engine_schemas::types::STRING20<Byte>;

    using value_type_tag = ::engine_schemas::schema::types::STRING20;
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
