// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.1.0
#pragma once
#include "schema/schema.hpp"
#include "types/OrderStatus.hpp"
#include "types/Side.hpp"
#include "types/OrderType.hpp"
#include "types/STRING36.hpp"
#include "types/STRING4.hpp"
#include "types/UINT32.hpp"
#include "types/UINT64.hpp"
#include "types/messageHeader.hpp"
#include "messages/order_schema.hpp"
